# ============================================================
# Ralph Wiggum Loop Runner (PowerShell)
# Generated by CC Native orchestrator — do not edit manually
# ============================================================

$ErrorActionPreference = "Stop"

# Config (filled by orchestrator)
$MaxIterations = {{MAX_ITERATIONS}}
$PromptFile = "{{PROMPT_FILE}}"
$LogFile = "{{LOG_FILE}}"
$WorkingDir = "{{WORKING_DIR}}"
$LockFile = "{{LOCK_FILE}}"
$MaxConsecutiveFailures = 3
$PerIterationTimeout = {{PER_ITERATION_TIMEOUT}}

function Write-Log {
    param([string]$Message)
    $Message | Tee-Object -FilePath $LogFile -Append
}

# Cleanup function
function Remove-LockFile {
    if (Test-Path $LockFile) {
        Remove-Item -Path $LockFile -Force
        Write-Log "Lock file removed. Ralph loop exited."
    }
}

try {
    Set-Location $WorkingDir

    $consecutiveFailures = 0

    Write-Log "=== Ralph Loop Started ==="
    Write-Log "Max iterations: $MaxIterations"
    Write-Log "Timeout per iteration: ${PerIterationTimeout}s"
    Write-Log "Working directory: $WorkingDir"
    Write-Log "Started: $(Get-Date -Format 'o')"
    Add-Content -Path $LogFile -Value "---"

    for ($i = 1; $i -le $MaxIterations; $i++) {
        Write-Log ""
        Write-Log "=== Ralph Iteration $i / $MaxIterations ==="
        Write-Log "Started: $(Get-Date -Format 'o')"

        $exitCode = 0
        $output = ""
        $timedOut = $false

        try {
            # Create a job to run claude with timeout
            # --setting-sources user: skip project hooks (context manager, plan review, etc.)
            # Ralph child instances must run without CC Native hooks — they're incompatible
            # with autonomous iteration (hooks inject prompts, block actions, create contexts)
            $job = Start-Job -ScriptBlock {
                param($promptPath)
                Get-Content $promptPath -Raw | claude --print --dangerously-skip-permissions --setting-sources user 2>&1
            } -ArgumentList $PromptFile

            # Wait with timeout
            $completed = $job | Wait-Job -Timeout $PerIterationTimeout

            if ($null -eq $completed) {
                # Timed out
                $job | Stop-Job
                $job | Remove-Job -Force
                $timedOut = $true
                $output = "TIMEOUT: Iteration exceeded ${PerIterationTimeout}s"
                $exitCode = 124
            } else {
                $output = $job | Receive-Job
                if ($job.State -eq "Failed") {
                    $exitCode = 1
                }
                $job | Remove-Job
            }
        } catch {
            $output = $_.Exception.Message
            $exitCode = 1
        }

        # Log output
        Add-Content -Path $LogFile -Value $output

        # Handle exit codes
        if ($timedOut) {
            Write-Log "TIMEOUT: Iteration $i exceeded ${PerIterationTimeout}s"
            $consecutiveFailures++
        } elseif ($exitCode -ne 0) {
            Write-Log "ERROR: Iteration $i exited with code $exitCode"
            $consecutiveFailures++
        } else {
            $consecutiveFailures = 0
        }

        # Abort on too many consecutive failures
        if ($consecutiveFailures -ge $MaxConsecutiveFailures) {
            Write-Log "ABORT: $MaxConsecutiveFailures consecutive failures. Stopping."
            exit 2
        }

        # Check for completion signal
        if ($output -match [regex]::Escape('<promise>COMPLETE</promise>')) {
            Write-Log "Ralph COMPLETED at iteration $i"
            Write-Log "Finished: $(Get-Date -Format 'o')"
            exit 0
        }

        Write-Log "Iteration $i finished: $(Get-Date -Format 'o')"
        Add-Content -Path $LogFile -Value "---"

        # Brief pause between iterations
        Start-Sleep -Seconds 2
    }

    Write-Log ""
    Write-Log "Ralph reached max iterations ($MaxIterations)"
    Write-Log "Finished: $(Get-Date -Format 'o')"
    exit 1

} finally {
    Remove-LockFile
}
