#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Ralph Wiggum Loop Runner (Bash)
# Generated by CC Native orchestrator — do not edit manually
# ============================================================

# Config (filled by orchestrator)
MAX_ITERATIONS={{MAX_ITERATIONS}}
PROMPT_FILE="{{PROMPT_FILE}}"
LOG_FILE="{{LOG_FILE}}"
WORKING_DIR="{{WORKING_DIR}}"
LOCK_FILE="{{LOCK_FILE}}"
MAX_CONSECUTIVE_FAILURES=3
PER_ITERATION_TIMEOUT={{PER_ITERATION_TIMEOUT}}

# Cleanup on exit (always remove lock file)
cleanup() {
  rm -f "$LOCK_FILE"
  echo "Lock file removed. Ralph loop exited." | tee -a "$LOG_FILE"
}
trap cleanup EXIT INT TERM

cd "$WORKING_DIR"
consecutive_failures=0

echo "=== Ralph Loop Started ===" | tee -a "$LOG_FILE"
echo "Max iterations: $MAX_ITERATIONS" | tee -a "$LOG_FILE"
echo "Timeout per iteration: ${PER_ITERATION_TIMEOUT}s" | tee -a "$LOG_FILE"
echo "Working directory: $WORKING_DIR" | tee -a "$LOG_FILE"
echo "Started: $(date -Iseconds)" | tee -a "$LOG_FILE"
echo "---" >> "$LOG_FILE"

for i in $(seq 1 $MAX_ITERATIONS); do
  echo "" | tee -a "$LOG_FILE"
  echo "=== Ralph Iteration $i / $MAX_ITERATIONS ===" | tee -a "$LOG_FILE"
  echo "Started: $(date -Iseconds)" | tee -a "$LOG_FILE"

  # Run claude with timeout, capture exit code
  # --setting-sources user: skip project hooks (context manager, plan review, etc.)
  # Ralph child instances must run without CC Native hooks — they're incompatible
  # with autonomous iteration (hooks inject prompts, block actions, create contexts)
  set +e
  OUTPUT=$(timeout "$PER_ITERATION_TIMEOUT" sh -c \
    'cat "$1" | claude --print --dangerously-skip-permissions --setting-sources user 2>&1' \
    -- "$PROMPT_FILE")
  EXIT_CODE=$?
  set -e

  # Log output
  echo "$OUTPUT" >> "$LOG_FILE"

  # Handle exit codes
  if [ $EXIT_CODE -eq 124 ]; then
    echo "TIMEOUT: Iteration $i exceeded ${PER_ITERATION_TIMEOUT}s" | tee -a "$LOG_FILE"
    consecutive_failures=$((consecutive_failures + 1))
  elif [ $EXIT_CODE -ne 0 ]; then
    echo "ERROR: Iteration $i exited with code $EXIT_CODE" | tee -a "$LOG_FILE"
    consecutive_failures=$((consecutive_failures + 1))
  else
    consecutive_failures=0
  fi

  # Abort on too many consecutive failures
  if [ $consecutive_failures -ge $MAX_CONSECUTIVE_FAILURES ]; then
    echo "ABORT: $MAX_CONSECUTIVE_FAILURES consecutive failures. Stopping." | tee -a "$LOG_FILE"
    exit 2
  fi

  # Check for completion signal
  if echo "$OUTPUT" | grep -qF '<promise>COMPLETE</promise>'; then
    echo "Ralph COMPLETED at iteration $i" | tee -a "$LOG_FILE"
    echo "Finished: $(date -Iseconds)" | tee -a "$LOG_FILE"
    exit 0
  fi

  echo "Iteration $i finished: $(date -Iseconds)" | tee -a "$LOG_FILE"
  echo "---" >> "$LOG_FILE"

  # Brief pause between iterations
  sleep 2
done

echo "" | tee -a "$LOG_FILE"
echo "Ralph reached max iterations ($MAX_ITERATIONS)" | tee -a "$LOG_FILE"
echo "Finished: $(date -Iseconds)" | tee -a "$LOG_FILE"
exit 1
