/**
 * Review tracker management — human-readable lifecycle summary.
 * Extracted from artifacts.ts.
 */

import * as fs from "node:fs";
import path from "node:path";

import { logWarn } from "../../../_shared/lib-ts/runtime/logger.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ReviewTrackerEntry {
  iteration: number;
  timestamp: string;
  planHash: string;
  verdict: string;
  decision: string;
  score: number;
  topIssues: string[];
  reviewFolder: string;
}

// ---------------------------------------------------------------------------
// Tracker Writing
// ---------------------------------------------------------------------------

/**
 * Build or update the review-tracker.md in the cc-native reviews directory.
 */
export function writeReviewTracker(
  ccNativeReviewsDir: string,
  entry: ReviewTrackerEntry,
): void {
  const trackerPath = path.join(ccNativeReviewsDir, "review-tracker.md");

  let existingContent = "";
  try {
    if (fs.existsSync(trackerPath)) {
      existingContent = fs.readFileSync(trackerPath, "utf8");
    }
  } catch {
    // Fresh start
  }

  const previousHashes = extractPreviousHashes(existingContent);
  const hashChanged = previousHashes.length > 0 &&
    previousHashes.at(-1) !== entry.planHash;

  const lines: string[] = [];
  const verdictEmoji = entry.decision === "allow" ? "\u2705" : "\u274C";
  const changeNote = previousHashes.length > 0
    ? (hashChanged ? "\u2705 Plan was revised (hash changed)" : "\u26A0\uFE0F Plan unchanged since last review")
    : "Initial review";

  lines.push(`## Iteration ${entry.iteration} \u2014 ${entry.timestamp} \u2014 ${verdictEmoji} ${entry.verdict.toUpperCase()}`);
  lines.push("");
  lines.push(`- **Decision:** ${entry.decision}`);
  lines.push(`- **Score:** ${entry.score.toFixed(2)}`);
  lines.push(`- **Plan hash:** \`${entry.planHash}\``);
  lines.push(`- **Status:** ${changeNote}`);
  lines.push(`- **Full review:** [\`${path.basename(entry.reviewFolder)}/\`](${path.basename(entry.reviewFolder)}/index.md)`);

  if (entry.topIssues.length > 0) {
    lines.push("");
    lines.push("**Top issues:**");
    for (const issue of entry.topIssues) {
      lines.push(`- ${issue}`);
    }
  }
  lines.push("");

  let output: string;
  if (!existingContent || !existingContent.includes("# Plan Review Tracker")) {
    output = [
      "# Plan Review Tracker",
      "",
      "> Auto-generated by plan review hook. Shows review lifecycle across iterations.",
      "> Check `plan.md` in each iteration folder to diff plan changes.",
      "",
      ...lines,
    ].join("\n");
  } else {
    output = existingContent.trimEnd() + "\n\n" + lines.join("\n");
  }

  try {
    fs.writeFileSync(trackerPath, output, "utf8");
  } catch (error) {
    logWarn("artifacts", `Failed to write review tracker: ${error}`);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function extractPreviousHashes(content: string): string[] {
  const hashes: string[] = [];
  const regex = /\*\*Plan hash:\*\* `([a-f0-9]+)`/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(content)) !== null) {
    hashes.push(match[1]!);
  }
  return hashes;
}


