import {promises as fs} from 'node:fs'
import {join} from 'node:path'

import {copyDir} from './template-installer.js'
import {getTemplatePath} from './template-resolver.js'

/**
 * BMAD version to install
 */
const BMAD_VERSION = '6.0.0-alpha.22'

/**
 * BMAD installation configuration
 */
interface BmadInstallConfig {
  projectName: string
  targetDir: string
  username: string
}

/**
 * Generate core module configuration YAML
 */
function generateCoreConfig(username: string): string {
  const now = new Date().toISOString()
  return `# CORE Module Configuration
# Generated by AI Workflow CLI
# Version: ${BMAD_VERSION}
# Date: ${now}

user_name: ${username}
communication_language: English
document_output_language: English
output_folder: "{project-root}/_bmad-output"
`
}

/**
 * Generate BMM module configuration YAML
 */
function generateBmmConfig(projectName: string, username: string): string {
  const now = new Date().toISOString()
  return `# BMM Module Configuration
# Generated by AI Workflow CLI
# Version: ${BMAD_VERSION}
# Date: ${now}

project_name: ${projectName}
user_skill_level: intermediate
planning_artifacts: "{project-root}/_bmad-output/planning-artifacts"
implementation_artifacts: "{project-root}/_bmad-output/implementation-artifacts"
project_knowledge: "{project-root}/docs"
tea_use_mcp_enhancements: false
tea_use_playwright_utils: false

# Core Configuration Values
user_name: ${username}
communication_language: English
document_output_language: English
output_folder: "{project-root}/_bmad-output"
`
}

/**
 * Generate installation manifest YAML
 */
function generateManifest(): string {
  const now = new Date().toISOString()
  return `installation:
  version: ${BMAD_VERSION}
  installDate: ${now}
  lastUpdated: ${now}
  installedBy: aiwcli
modules:
  - core
  - bmm
ides:
  - claude-code
`
}


/**
 * Install BMAD structure in target directory
 */
export async function installBmad(config: BmadInstallConfig): Promise<void> {
  const {projectName, targetDir, username} = config

  // Get bundled BMAD template path (parent directory containing _bmad/ and .claude/)
  const templateRootPath = await getTemplatePath('bmad')

  const bmadPath = join(targetDir, '_bmad')
  const claudePath = join(targetDir, '.claude')

  // Create main _bmad directories
  await fs.mkdir(join(bmadPath, '_config'), {recursive: true})
  await fs.mkdir(join(bmadPath, 'core'), {recursive: true})
  await fs.mkdir(join(bmadPath, 'bmm'), {recursive: true})

  // Create output directories
  await fs.mkdir(join(targetDir, '_bmad-output', 'planning-artifacts'), {recursive: true})
  await fs.mkdir(join(targetDir, '_bmad-output', 'implementation-artifacts'), {recursive: true})

  // Copy _bmad/ structure from template
  const templateBmadPath = join(templateRootPath, '_bmad')

  // Copy core module from template
  const templateCorePath = join(templateBmadPath, 'core')
  const targetCorePath = join(bmadPath, 'core')
  await copyDir(templateCorePath, targetCorePath)

  // Copy BMM module from template
  const templateBmmPath = join(templateBmadPath, 'bmm')
  const targetBmmPath = join(bmadPath, 'bmm')
  await copyDir(templateBmmPath, targetBmmPath)

  // Copy _config directory (manifest CSVs, ides, etc.) from template
  const templateConfigPath = join(templateBmadPath, '_config')
  const targetConfigPath = join(bmadPath, '_config')
  await copyDir(templateConfigPath, targetConfigPath)

  // Copy .claude/commands/bmad/ structure from template
  const templateClaudeBmadPath = join(templateRootPath, '.claude', 'commands', 'bmad')
  const targetClaudeBmadPath = join(claudePath, 'commands', 'bmad')
  await copyDir(templateClaudeBmadPath, targetClaudeBmadPath)

  // Generate and write custom configuration files (overwrite template configs)
  await fs.writeFile(join(targetCorePath, 'config.yaml'), generateCoreConfig(username), 'utf8')
  await fs.writeFile(join(targetBmmPath, 'config.yaml'), generateBmmConfig(projectName, username), 'utf8')
  await fs.writeFile(join(targetConfigPath, 'manifest.yaml'), generateManifest(), 'utf8')
}

