"""Base utilities for shared context management."""
from .atomic_write import atomic_write, atomic_append
from .constants import (
    OUTPUT_DIR,
    CONTEXTS_DIR,
    INDEX_FILENAME,
    validate_context_id,
    get_output_dir,
    get_contexts_dir,
    get_context_dir,
    get_context_plans_dir,
    get_context_handoffs_dir,
    get_index_path,
    get_context_file_path,
    get_events_file_path,
)
from .utils import (
    eprint,
    now_local,
    now_iso,
    project_dir,
    sanitize_filename,
    sanitize_title,
    generate_context_id,
)
from .logger import (
    hook_log,
    log_debug,
    log_info,
    log_warn,
    log_error,
    log_hook_error,
    set_context_path,
)

__all__ = [
    "atomic_write",
    "atomic_append",
    "OUTPUT_DIR",
    "CONTEXTS_DIR",
    "INDEX_FILENAME",
    "validate_context_id",
    "get_output_dir",
    "get_contexts_dir",
    "get_context_dir",
    "get_context_plans_dir",
    "get_context_handoffs_dir",
    "get_index_path",
    "get_context_file_path",
    "get_events_file_path",
    "eprint",
    "now_local",
    "now_iso",
    "project_dir",
    "sanitize_filename",
    "sanitize_title",
    "generate_context_id",
    "hook_log",
    "log_debug",
    "log_info",
    "log_warn",
    "log_error",
    "log_hook_error",
    "set_context_path",
]
